//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingCompany.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Material
    {
        public int Supply_id { get; set; }
        public int Material_id { get; set; }
        public decimal Cost { get; set; }
        public decimal Count { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
